### Get User Data
GET http://localhost/apisirs/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0OCwiamVuaXNfdXNlcl9pZCI6MywibmFtYSI6IkRpbmtlcyBLb3RhIEJla2FzaSIsImVtYWlsIjoiMzI3NSIsInJzSWQiOiIzMjc1IiwiaWF0IjoxNjc5OTkyMjY4LCJleHAiOjE2ODUxNzYyNjh9.UwJyBRhNHK37iheXU8ZCskKJjzArv7Z41vSSXYLq0DM

###
GET http://localhost/apisirs/rllimatitiksatu?tahun=2022-02-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMzLCJuYW1hIjoiUlMgS2Fua2VyIERoYXJtYWlzIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzUyNjE0NjYsImV4cCI6MTY3NTI2MjM2Nn0.z9XFaXu9MijOkjsQf8wJ1YtIEizLnkq07vewBoLUg6U

### Logut
DELETE http://localhost/apisirs/logout

### Get Token
GET http://localhost/apisirs/token

### Reference
##################################################
### Jenis Kegiatan
GET http://sirs6.kemkes.go.id/apisirs/jeniskegiatan?rlid=7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWEiOiJSUyBVbXVtIERhZXJhaCBLYWJ1cGF0ZW4gQWNlaCBCZXNhciIsImVtYWlsIjoiMTEwODAxNSIsInJzSWQiOiIxMTA4MDE1IiwiaWF0IjoxNjc1MTUxNzY0LCJleHAiOjE2NzUxNTUzNjR9.fgYUuWu5HUFP48Q8jW0u8bcTKSkqJuyR7DPaSJJIMvQ


### Jenis Pelayanan
GET http://sirs6.kemkes.go.id/apisirs/jenispelayanan?rlid=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQwMzcxMDEsImV4cCI6MTY3NDAzNzE2MX0.T_4ek7zpmyzCq-CIK6sWUrqjgukVyVlhJCmFuLI20lk

### Jenis Tindakan
GET http://localhost/apisirs/jenistindakan?rlid=9
##################################################

### ADMIN DINKES

### LOGIN
POST http://localhost:8000/apisirs/loginadmin
Content-Type: application/json

{
    "userName": "32",
    "password": "12345"
}


### Logut
DELETE http://localhost:8000/apisirsadmin/logout

### Get Token
GET http://localhost:8000/apisirsadmin/token

### GET DATA KAB/KOTA
GET http://localhost:8000/apisirs/kabkota
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjgwMTgzNDAzLCJleHAiOjE2ODUzNjc0MDN9.OIdpb-qqYt7SgGJEKKLp5xvxzwYhPJ-m47KFXPQVfUA

### GET DATA RS BY KAB/KOTA
GET http://localhost:8000/apisirs/rumahsakit?kabkotaid=3173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjc5OTk2OTA1LCJleHAiOjE2ODUxODA5MDV9.fhfF6pWswxsSiXKSb4djEjXSHveF5lof6oOE8L1RSTM

### INPUT VALIDASI


### GET DATA RL 1.3
GET http://localhost:8000/apisirsadmin/rlsatutitiktiga/?koders=3171665&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NiwiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6IkRLSSBQcm92aW5zaSAiLCJlbWFpbCI6IjMxIiwicnNJZCI6IjMxIiwiaWF0IjoxNjc5OTk1MTExLCJleHAiOjE2ODUxNzkxMTF9.0qEp100vkjPZg78JWd7BYJuARe8t_MkrGixvS6iL5ms


### GET DATA RL 3.1
GET http://localhost:8000/apisirsadmin/rltigatitiksatu/?koders=3174063&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NiwiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6IkRLSSBQcm92aW5zaSAiLCJlbWFpbCI6IjMxIiwicnNJZCI6IjMxIiwiaWF0IjoxNjc5OTk1MTExLCJleHAiOjE2ODUxNzkxMTF9.0qEp100vkjPZg78JWd7BYJuARe8t_MkrGixvS6iL5ms

### GET DATA RL 36
GET http://localhost:8000/apisirsadmin/rltigatitikenam/?koders=3216218&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0OCwiamVuaXNfdXNlcl9pZCI6MywibmFtYSI6IkRpbmtlcyBLb3RhIEJla2FzaSIsImVtYWlsIjoiMzI3NSIsInJzSWQiOiIzMjc1IiwiaWF0IjoxNjgwMTAxMzQ1LCJleHAiOjE2ODUyODUzNDV9.zs_FfDy5-Mnabi9OW5j3WaFrEo0JZA43w2i0Ms157Tc

### GET DATA RL 39
GET http://localhost:8000/apisirsadmin/rltigatitiksembilan/?koders=3216218&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjc5OTk2OTA1LCJleHAiOjE2ODUxODA5MDV9.fhfF6pWswxsSiXKSb4djEjXSHveF5lof6oOE8L1RSTM

### GET DATA RL 4B
GET http://localhost:8000/apisirsadmin/rlempatb/?koders=3171665&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NiwiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6IkRLSSBQcm92aW5zaSAiLCJlbWFpbCI6IjMxIiwicnNJZCI6IjMxIiwiaWF0IjoxNjc5OTk1MTExLCJleHAiOjE2ODUxNzkxMTF9.0qEp100vkjPZg78JWd7BYJuARe8t_MkrGixvS6iL5ms

### GET DATA RL 4B SEBAB
GET http://localhost:8000/apisirsadmin/rlempatbsebab/?koders=3171665&tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NiwiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6IkRLSSBQcm92aW5zaSAiLCJlbWFpbCI6IjMxIiwicnNJZCI6IjMxIiwiaWF0IjoxNjc5OTk1MTExLCJleHAiOjE2ODUxNzkxMTF9.0qEp100vkjPZg78JWd7BYJuARe8t_MkrGixvS6iL5ms

### Validasi Input
POST http://localhost:8000/apisirsadmin/validasi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjc5OTk0OTg0LCJleHAiOjE2ODUxNzg5ODR9.DWijs60oUGeQx1ZkQj5e2WuSJ8dXih4nfr1QU8UrW8E

{
    "rsId": "3171665",
    "rlId": "14",
    "tahun": "2022-01-01",
    "statusValidasiId":1,
    "catatan": "SUCCESS"
}

### Validasi Update
PATCH http://localhost:8000/apisirsadmin/validasi/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjc5OTk1OTg3LCJleHAiOjE2ODUxNzk5ODd9.7AVWsbOLC1x7wsSfWjn8SgznNQgCR1Lx-ZND6xt4p8I

{
    "statusValidasiId":2,
    "catatan":"sudah divalidasi jangan lupa bayar"
}

### GET DATA Validasi
GET http://localhost:8000/apisirsadmin/validasi/?rsid=3216218&rlid=6&tahun=2022-01-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA0NywiamVuaXNfdXNlcl9pZCI6MiwibmFtYSI6Ikphd2EgQmFyYXQiLCJlbWFpbCI6IjMyIiwicnNJZCI6IjMyIiwiaWF0IjoxNjc5OTk0OTg0LCJleHAiOjE2ODUxNzg5ODR9.DWijs60oUGeQx1ZkQj5e2WuSJ8dXih4nfr1QU8UrW8E

### GET PILIHAN VALIDASI
GET http://localhost:8000/apisirsadmin/statusvalidasi/